"""Initial migrations

Revision ID: 007d203802ba
Revises: 
Create Date: 2026-02-22 16:06:29.419544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '007d203802ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('necmultiplechoicequestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subchapter_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subchapter_id'], ['necsyllabussubchapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_necmultiplechoicequestion_question'), 'necmultiplechoicequestion', ['question'], unique=False)
    op.create_table('necmultiplechoiceanswer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['necmultiplechoicequestion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_necmultiplechoiceanswer_answer'), 'necmultiplechoiceanswer', ['answer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_necmultiplechoiceanswer_answer'), table_name='necmultiplechoiceanswer')
    op.drop_table('necmultiplechoiceanswer')
    op.drop_index(op.f('ix_necmultiplechoicequestion_question'), table_name='necmultiplechoicequestion')
    op.drop_table('necmultiplechoicequestion')
    # ### end Alembic commands ###
