"""description field added to nec program

Revision ID: d7dd0a2f01ad
Revises: 31bbf49c3c63
Create Date: 2026-02-23 21:50:38.585619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd7dd0a2f01ad'
down_revision: Union[str, Sequence[str], None] = '31bbf49c3c63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program', 'description')
    # ### end Alembic commands ###
